### ISSUE TITLE
ÌndexError(list index out of range)

### ISSUE THREAD

**Issue by nman999** [mancuniancol/script.quasar.torrentz-mc#2]
Im getting this error when searching for links, this is happening for movies, not for tv shows as far as i know, although that might be due to the fact that i also have the EZTV provider enabled so the links for tv shows, might be (really) coming from that provider (even though in the list they appear to be coming from the Torrentz provider),
thanks in advance,

**Comment by mancuniancol** [comment]
Which version do you have? I've supposed to fix that in version 1.2.2

**Comment by nman999** [comment]
Im using version 1.2.1, which is the last one that shows up in the Releases page in Github, how can I get 1.2.2?

**Comment by mancuniancol** [comment]
https://github.com/mancuniancol/script.quasar.torrentz-mc/archive/v1.2.2.zip

**Comment by nman999** [comment]
Thanks. 1.2.2 is working. The icon in the results list is not the one from the script though.
thanks again.

**Comment by mancuniancol** [comment]
The icon changes when the magnet is provider for several providers. I will close this issue
